@startuml

      (*)-->[每天]定时任务同步供应链发货数据
      -->"ddd"
      -->"dsjo"
      -->[D+N为打折期]"筛选出打折期范围内的所有商品"

      -->"生成检查单;同步检查表;"
  if "PDA人工检查" then
    -->[批次存在] "新增到提醒表"
     --> (*)
  else
    -right->[批次不存在] "更新检查表sku状态"
    --> === 系统筛选完成 ===
    --> (*)
  endif

@enduml