
@startuml
scale 600 width
[*] -down->待检查 :在M天内的
待检查:同步数据中满足需要检查条件的数据

待检查 -d-> 已检查批次不存在
已检查批次不存在-down->[*]

待检查 -d-> 已检查批次存在
state 已检查批次存在 {
[*] -d->已检查无需处理:批次时间(打折时间/废弃时间)N天以外
已检查无需处理-d->待检查:记录次数+1


[*] ->已检查待提醒:批次时间(打折时间/废弃时间)N天以内

已检查待提醒 -d->已废弃
已下架 -d->[*]

已检查待提醒 -d->已打折
已打折-l->已检查待提醒:废弃时间N天以内
}

@enduml
