@startuml

scale 600 width
[*] --> 初始状态
初始状态:每天同步的供应链收货数据的原始状态


初始状态 -left->无需检查 :M天以外的
无需检查 --> [*]

初始状态 -down->待检查 :在M天内的
待检查:同步数据中满足需要检查条件的数据

待检查 -down-> 已检查批次不存在
已检查批次不存在-down->[*]

待检查 -down-> 已检查批次存在

已检查批次存在 -right->已检查无需处理
已检查无需处理-down->[*]:记录次数

已检查批次存在 -down->已检查待下架
已检查待下架 -down->[*]:在提醒单中执行下架操作

@enduml